DROP TABLE IF EXISTS PAYMENT;

CREATE TABLE PAYMENT (
   id INT AUTO_INCREMENT  PRIMARY KEY,
   brand VARCHAR(250) NOT NULL,
   reference VARCHAR(250) NOT NULL,
   amount INT DEFAULT NULL,
   status VARCHAR(250) NOT NULL
);
